### PR TITLE
Accommodate breaking changes in geometry

### PR DESCRIPTION
**Pull request by knoepfel**
Pursuant to LArSoft/larcorealg#34.

### CODE REVIEW

**Comment by calcuttj** [comment]
trigger build with DUNE/protoduneana#12 DUNE/duneopdet#22 DUNE/dunesw#45 DUNE/dunesim#28 DUNE/dunereco#34 DUNE/duneprototypes#19 DUNE/dunedataprep#15 DUNE/duneana#20

**Comment by calcuttj** [comment]
trigger build with DUNE/protoduneana#12 DUNE/duneopdet#22 DUNE/dunesw#45 DUNE/dunesim#28 DUNE/dunereco#34 DUNE/duneprototypes#19 DUNE/dunedataprep#15 DUNE/duneana#20

**Comment by calcuttj** [comment]
@knoepfel Seems like something might be going on in ClusterCrawlerAlg after these changes. I made a DUNE release last night (based off of larsoft v09_64_01) and there were no seg faults in that algorithm.

**Comment by knoepfel** [comment]
Thanks, @calcuttj, for the heads-up.  I'll take a look first thing on Monday—is that an acceptable time frame?

**Comment by calcuttj** [comment]
I think so -- with the holidays coming up I think demand for new releases will be low

**Comment by calcuttj** [comment]
Additionally/interestingly -- it seems to be compiler dependent. c7 build is not crashing while e20 is

**Comment by knoepfel** [comment]
@calcuttj, I think I see the problem--it looks like an uninitialized variable to me (`plane`), which can have different behavior in GCC vs. Clang.  I'll work on it on Monday, and we should be able to put out a bug fix release relatively early in the week.  Sorry about the headache.

**Comment by calcuttj** [comment]
No problem, thanks for looking into it

**Comment by knoepfel** [comment]
@calcuttj, I have a fix ready (https://github.com/LArSoft/larreco/pull/49), and I confirm that it addresses the problem.  We hope to put out a new LArSoft release by sometime tomorrow.

**Pull request merged**
