### PR TITLE
Addition of FR-4 material in the FD HD geometry

### PR DESCRIPTION
**Pull request by vpec0**
On request by Juergen Reichenbacher and the Low-E working group, I created a new approximation of FR-4 material within the HD geometry. This material is necessary for proper background simulations. 

APA wire boards were made of G-10, the design if FR-4. The readout boards were missing completely. The cathode was only approximated by an extremely thin layer of stainless steel, while the design is the cathode is made of FR-4 boards laminated with Kapton.

Juergen's group is now going to test the geometry.

Changes:
1) All APA boards are now 3/16 in = 4.76 mm thick, which corresponds to the specs in TDR. I attribute the greater thickness of the stack of 4 readout boards done by you as a result of having the wires + solder in between the boards.
2) I added a box of FR-4 at the readout head of each APA, approximating the 2 stacks of readout boards. The box is 3.81 cm thick (2\*4\*4.76 mm), 16.5 cm in the vertical direction, and as wide as the APA frame.
3) I changed the CPA to FR-4, and increased its thickness to 3 mm. The CPA modelling still does not correspond the reality, but the material budget is close enough.

### CODE REVIEW

**Comment by tomjunk** [comment]
Approved.

**Review by tomjunk — APPROVED** [review]

**Comment by vpec0** [comment]
The change to the HD gdml files with 54ead63 was casusing CI test failures. @tomjunk reverted the commit with ecd49c0. I am investigating the cause. The change in the thickness of wire boards changed the with of the APA and as a consequence, lowered the number of U and V wires by 1 on each side of the APA. This is most likely the reason for the fail.

**Comment by vpec0** [comment]
There are 3 new commits in vpec0:feature/vpec-fd-hd-fr4-boards that make the wire layout identical to the version before the FR-4 update. This is a temporary fix to have working geometry with the right material budget but the wire setup unchagend.

Relevant commits: 92058434d3de16fdd2680aaa01d044b6e91c2eb4, 44d9653805e55b4d00901c019c400605efed0403, 4b509a9eff0722b48dd643c8ccb5003f5ba459b0

**Comment by vpec0** [comment]
A fix was merged into develop within PR #92.

**Pull request merged**
