### PR TITLE
Don't forget to set drift direction

### PR DESCRIPTION
**Pull request by knoepfel**

### CODE REVIEW

**Comment by tomjunk** [comment]
I had a fix where either the axis or the sign changes to increment ncell and it seems to work.  I haven't tried this version where only the axis is required to be the same within a cell.  I suspect that the axis is constant for all the detectors and only the sign varies from one place to another in a detector.  What is a "cell"?

**Comment by tomjunk** [comment]
I put a fix in https://github.com/DUNE/dunecore/pull/118

**Comment by knoepfel** [comment]
Thanks, Tom.  I like yours better.

**Comment by tomjunk** [comment]
Thanks -- closing PR.  We're working on a couple of other issues -- ProtoDUNE-DP reco CI and an issue with T0 and drift position (again!) in ProtoDUNE-SP reco CI.

**Pull request closed without merging**
