### PR TITLE
Updating larsoft

### PR DESCRIPTION
**Pull request by calcuttj**
Need this to test duneana/#64

### CODE REVIEW

**Comment by calcuttj** [comment]
trigger build with DUNE/duneana#64

**Comment by calcuttj** [comment]
trigger build with #112 DUNE/duneana#64

**Comment by calcuttj** [comment]
trigger build with DUNE/dunereco#104

**Comment by calcuttj** [comment]
trigger build with DUNE/duneprototypes#49

**Comment by tomjunk** [comment]
Canceling this PR as it seems to be just an enabler to test a PR that's already merged.

**Pull request closed without merging**
