### PR TITLE
Update to dunedetdataformats v4_1_0 and dunedaqdataformats v4_0_0

### PR DESCRIPTION
**Pull request by tomjunk**
Update to dunedetdataformats v4_1_0 and dunedaqdataformats v4_0_0

Some DAQ-supplied classes are updated, and most of the changes that are exposed to us have to do with their new namespaces.  The namespaces are part of the TBranch names for the trigger primitive, trigger activity and trigger candidate classes as these are directly used in the output ROOT files.

I also added some missing version lines in dunecore/DuneObj/classes_def.xml and now TTree:Draw works.

There is a corresponding PR in duneprototypes.

### CODE REVIEW

**Comment by tomjunk** [comment]
This PR is coupled to

https://github.com/DUNE/duneprototypes/pull/29

in duneprototypes.

**Comment by calcuttj** [comment]
Resolved a conflict after larsoft + dependency updates

**Comment by calcuttj** [comment]
trigger build

**Comment by calcuttj** [comment]
Don't know why I started the build on this one without the other ...

**Review by calcuttj — APPROVED** [review]

**Pull request merged**
