### PR TITLE
add in the class defs needed for assns

### PR DESCRIPTION
**Pull request by wesketchum**

### CODE REVIEW

**Comment by tomjunk** [comment]
Looks okay, but I have some comments on the duneprototypes PR.  This also may break anyone's code that relies on the old way of unpacking TP, TA and TCs.  I don't believe there are any such people at the moment, though.

**Comment by tomjunk** [comment]
Since it is a breaking change (removes some class defs), I'll hold off merging until just before the next release.  And work on the duneprototypes PR needs to be done.

**Comment by wesketchum** [comment]
Agree that we can wait to merge it in until closer to a release. We can also bring back the map of source IDs to trigger objects -- this is maybe a point for some discussion, but I don't think that we should be storing the trigger objects by source ID, as I think that SourceIDs are intended to be more of an internal DAQ bookkeeping thing and shouldn't persist like this to the offline.

**Review by tomjunk — APPROVED** [review]
I'm surprised merging the associated duneprototypes PR didn't require this.  Maybe one would only notice trying to read the rootfiles.  Merging now.

**Pull request merged**
