### PR TITLE
Add configuration for full FD HD geometry v6

### PR DESCRIPTION
**Pull request by vpec0**
This completes #127.

### CODE REVIEW

**Comment by absolution1** [comment]
Thanks @vpec0 
The inclusion of a dune10k_base_geo for all others to inherit of is a great way forward.
I've run a search in github of the places that currently use dune10kt_geo as part of a fcl block: https://github.com/search?q=org%3ADUNE+dune10kt_geo&type=code

This is probably too paranoid but most (not all) of these will need to be updated to use the dune10kt_base_geo block to maintain their functionality.

**Comment by absolution1** [comment]
I'll mark this PR as draft while we prepare a PR for the other blocks.

**Review by absolution1 — COMMENTED** [review]
Hi @vpec0 
It looks like this PR also includes the GDML.  These could be removed as that are included in PR 127

**Comment by vpec0** [comment]
> There are also fcls using dune10kt_geo in dunesw, but I'm not planning on updating them, as they should be tied to the latest geometry.

Interesting. If they are supposed to point to the latest geometry, then they haven't been doing that up until now.

**Comment by aolivier23** [comment]
@absolution1 may I review and merge this, or does it need to wait?

**Comment by vpec0** [comment]
> Hi @vpec0 It looks like this PR also includes the GDML. These could be removed as that are included in PR 127

This is PR is made from a branch based on the branch in #127. So they share commits. If this one is merged first, it would resolve #127 automatically.

**Review by aolivier23 — APPROVED** [review]
Changes to GDMLs will be tested with CI.

**Pull request merged**
