### PR TITLE
Feature/vpec vd tpc enclosure

### PR DESCRIPTION
**Pull request by vpec0**
Adding a single enclosure volume to contain all `volTPC` placements. 

This modification is done to FD VD, new perl script version, v6. Default configs for v6 geometry are added. However, default VD geometry to be loaded is still v5.  

Reason: Include `SimEenrgyDeposits` throughout the active volume in output products
  - Placements of `volTPC` have gaps in between each other (gaps are between pairs of TPCs).
  - At the largeant stage, only `SimEnergyDeposit`s are stored by volume name.
  - Largeant is configured to store them in `volTPC`. `volTPC`s were placed directly in `volCryostat`, therefore, if the gaps are to be included, we would need to store deposits in the whole cryostat.
  - Instead, creation of an enclosure of the active volume as a single logical volume allows configuring largeant to save deposits only in the active volume.

`LArG4DetectorService` needs to be configured with 
```
    LArG4DetectorService_LABEL.volumeNames: ["volTPCActive", "volTPCEnclosure",...]
    LArG4DetectorService_LABEL.stepLimits: [0.4, 0.4]
```

and, for later processing, `IonAndScint` producer needs to be configured with
```
  IonAndScint_LABEL.Instances: "LArG4DetectorServicevolTPCActive;LArG4DetectorServicevolTPCEnclosure"
```

### CODE REVIEW

**Comment by vpec0** [comment]
I just noticed that larsoft v10 comes with breaking changes to the geometry and I will need to accommodate to them.

**Comment by vpec0** [comment]
There was an issue with interference of the naming of the TPC volume encapsulation with the Geometry Builder algorithm to find TPC volumes. Because the enclosure's name started with volTPC, it was recognised as a single TPC volume by the builder, which was causing issues in the downstream processing. I changed the volume's name from volTPCEnclosure to volEnclosureTPC in commits [8e8fa96](https://github.com/DUNE/dunecore/pull/108/commits/8e8fa96afa19994ffabd89a206f3b033ac237778) and [dcf31a5](https://github.com/DUNE/dunecore/pull/108/commits/dcf31a532cb8198c9101a0c5a8c3541eb58f90b8).

**Review by lpaulucc — APPROVED** [review]
Hi Viktor, thank you for this. It looks like a very straightforward change and if this fixes a problem, I am happy to approve it. Is there already another PR to address the changes needed in larg4?

**Comment by vpec0** [comment]
> Hi Viktor, thank you for this. It looks like a very straightforward change and if this fixes a problem, I am happy to approve it. Is there already another PR to address the changes needed in larg4?

No, those changes need to be merged in and the config for the new geometry needs to be updated accordingly. There hasn't been a working v10 version of dunesw, has there?
Maybe a separate PR? This one should go in before PR #118 does. And a new one should go with #118.

**Comment by lpaulucc** [comment]
I don't think v10 is out yet... We can prepare the other PRs once we are ready to put this one in

**Comment by lgarren** [comment]
@lpaulucc  larsoft has just released v10_00_02.  FYI

**Comment by lpaulucc** [comment]
Thanks for the info, @lgarren!

**Review by absolution1 — APPROVED** [review]
Thanks for this @vpec0

**Comment by jroto** [comment]
Hi @vpec0, @lpaulucc, I was having a look at this PR just in case we would need to do the same for protodunevd...

Just one comment: I don't get why you want to store the edeps from the gaps in volTPC. In principle, by definition, these edeps are from outside the AV, and the TPC is not sensitive to them. They were never simulated/stored, until I added volCryostat to store the edeps from the non-active part for the arapucas.
Moreover, if I understand correctly and you remove volCryostat from LArG4DetectorService as suggested above, this would prevent us from storing energy deposits from the argon buffer, i.e., the membrane XArapucas would stop detecting light from the argon outside the AV. Is this intended?

**Comment by vpec0** [comment]
@jroto  
> I don't get why you want to store the edeps from the gaps in volTPC. In principle, by definition, these edeps are from outside the AV, and the TPC is not sensitive to them.

I can comment on this part. There is a drift field in the gaps between volumes belonging to individual CRPs. Charge there will be collected and should be taken into account in simulations. We are talking about the gaps inside the drift volume, not only within the CRP plane.

As for the full volCryostat, I can't comment on what the plan is regarding the light simulations.

**Comment by jroto** [comment]
> @jroto
> 
> > I don't get why you want to store the edeps from the gaps in volTPC. In principle, by definition, these edeps are from outside the AV, and the TPC is not sensitive to them.
> 
> I can comment on this part. There is a drift field in the gaps between volumes belonging to individual CRPs. Charge there will be collected and should be taken into account in simulations. We are talking about the gaps inside the drift volume, not only within the CRP plane.
> 
> As for the full volCryostat, I can't comment on what the plan is regarding the light simulations.

We never simulated that, also if they are gaps is because there is no electronics to readout that signal. Also, did you test it? I would say [LArSoft wouldn't even know to which wire assigns those electron clusters.](https://github.com/LArSoft/larsim/blob/a4621ff85b9ff9acdc64ddea7d0e728a146da534/larsim/ElectronDrift/SimDriftElectrons_module.cc#L269)

**Comment by vpec0** [comment]
This is only the first step towards the proper simulation. Anselmo Meregaglia is pushing towards having detsim/wirecell capable of dealing with such charge.

Although the gap is not instrumented, the electric field will drift the electrons towards the instrumented parts.

**Comment by lpaulucc** [comment]
@jroto you can take a look at this presentation for more info on the request for the gaps https://indico.fnal.gov/event/66234/contributions/300101/attachments/181948/249704/FDsimreco_ginevra.pdf. In any case, this would cause and impact for the photon yield since PD will be able to see the light produced by Edeps on the gaps and this is not being account for in the simulation. 
Regarding the volCryostat, I don't actually follow why this would be removed from the larg4 detector service... am I missing something here?

**Comment by jroto** [comment]
Thanks for the link, Laura! Much clearer now!

My comment about not removing volCryostat is due to Viktor's comment above (he forgot to include volCryostat):

> * 
> 
> 
> `LArG4DetectorService` needs to be configured with
> 
> ```
>     LArG4DetectorService_LABEL.volumeNames: ["volTPCActive", "volTPCEnclosure",]
>     LArG4DetectorService_LABEL.stepLimits: [0.4, 0.4]
> ```

Just remember to keep it when changing this.

**Comment by lpaulucc** [comment]
Thanks, @jroto . I am glad you noticed that! Yes, we cannot forget volCryostat!

**Comment by vpec0** [comment]
Develop has been merged here, with the transition to larsoft v10.

Default FD VD geometry version stays at v5. v6 with the enclosure needs to be configured explicitly using table `dunevd10kt_1x8x6_3view_30deg_v6_geo`.

**Pull request merged**
